### ISSUE TITLE
Draw mouse cursor

### ISSUE THREAD

**Issue by Rectus** [Hotrian/OpenVRDesktopDisplayPortal#24] opened 2016-08-09 14:16 UTC
Would it be possible to track the mouse cursor, and replicate it onto the overlay when the cursor is over it? If so, it would be a very useful feature for multitasking.

**Comment by Hotrian** [comment] 2016-08-09 20:20
Yes, this exists in the current source, it just hasn't been released yet. I'm still doing some final polishing and feature changes before the next release, but it should be out in the next day or two. I believe it was added in c5fe72fdb30ca184f2ff3dc7b44d7c734bd703c1 to be specific. This is part of #18.

**Comment by Rectus** [comment] 2016-08-09 21:47
Oh, nice work. That should teach me to read the commits before asking.

**Comment by Hotrian** [comment] 2016-08-09 22:44
No worries :) I should release very soon but I'm doing some last minute polishing before v1.0.5 :). The issues I've marked with the 1.0.5 milestone should all be closed very soon.

**Comment by Hotrian** [comment] 2016-08-10 03:47
I think I just finished all the changes I wanted to make for v1.0.5, so I'm doing final testing now to ensure everything works as intended, then pushing the release :D. Will close this issue after v1.0.5 releases.

**Closed as completed** 2016-08-10 08:06 UTC
Labels: Feature Request
